### ISSUE TITLE
Install Error on Linux Mint 20.3 Cinnamon

### ISSUE THREAD

**Issue by aut0mat3d** [BrianPugh/gnwmanager#79]
Ran into Trouble with the Install Instructions.
-installed via pip install gnwmanager which worked...

Non- working procedere as suggested in Install Instructions:
Uninstalled Python 2
pip uninstall pipx
rm -Rf ~/.local/share/pipx
reinstalled pipx

Environment:
Linux Mint 20.3 Cinnamon
Python Version: 3.8.10

Problem:
Install of gnwmanager is not possible - ends with Error:

Commands applied to install:
pip3 install --user pipx
pipx install gnwmanager
-Output:
```
Fatal error from pip prevented installation. Full pip output in file:
    /home/xxx/.cache/pipx/log/cmd_2023-12-07_10.49.33_pip_errors.log

pip failed to build package:
    intervaltree

Error installing gnwmanager.
```
Error Log:
```
----- snip ----
Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
Using cached importlib_resources-6.1.1-py3-none-any.whl (33 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Using cached cffi-1.16.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (444 kB)
Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: intervaltree
Failed to build intervaltree

PIP STDERR
----------
  WARNING: Building wheel for intervaltree failed: [Errno 13] Keine Berechtigung: '/home/raobereg/.cache/pip/wheels/45'
ERROR: Could not build wheels for intervaltree, which is required to install pyproject.toml-based projects
```

**Comment by BrianPugh** [comment]
between this and the other Mint issue #65, I'll spin up a Mint VM and see what's up. Generally, this seems more of like a python-environment issue rather than a gnwmanager-specific issue. I'll see what I can do to make it more accessible, though.

**Comment by BrianPugh** [comment]
closing this issue to focus on #65 . This seems to be an individual environment isssue. If you are still running into environment issues we can reopen or try to debug live on this discord.
